schedule: "0 * * * *"

streamer:
  name: "<name_here>"
  twitchName: "<twitch_name_here>"

image:
  repository: ghcr.io/liofal/youtube-dl:master
  tag: 2.3.1
  pullPolicy: Always

nfs:
  server: <server_ip_here>
  path: /<volume>/<folder>