apiVersion: batch/v1
kind: CronJob
metadata:
  name: youtube-dl-{{ .Values.streamer.name }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: youtube-dl-{{ .Values.streamer.name }}
        spec:
          serviceAccountName: youtube-dl-{{ .Values.streamer.name }}
          containers:
          - name: youtube-dl-{{ .Values.streamer.name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            envFrom:
            - configMapRef:
                name: youtube-dl-config-{{ .Values.streamer.name }}
            volumeMounts:
            - name: twitch-volume
              mountPath: /download
        {{- if .Values.cleanup.enabled }}
          - name: youtube-dl-{{ .Values.streamer.name }}-cleanup
            image: busybox
            command: ["/bin/sh", "-c"]
            args:
              - |
                STREAM_DIR=$(find /download -maxdepth 1 -type d -iname '{{ .Values.streamer.twitchName }}' | head -n 1)
                if [ -z "$STREAM_DIR" ]; then
                  echo "No download directory found for {{ .Values.streamer.twitchName }}, skipping cleanup."
                  exit 0
                fi

                echo "Listing files older than {{ .Values.cleanup.daysOld }} days in $STREAM_DIR:"
                find "$STREAM_DIR" -type f -mtime +{{ .Values.cleanup.daysOld }} -name '*.mp4'
                echo "Removing files older than {{ .Values.cleanup.daysOld }} days in $STREAM_DIR:"
                find "$STREAM_DIR" -type f -mtime +{{ .Values.cleanup.daysOld }} -name '*.mp4' -exec rm {} +
                echo "Cleanup completed."
            volumeMounts:
              - name: twitch-volume
                mountPath: /download
        {{- end }}
          restartPolicy: OnFailure
          volumes:
          - name: twitch-volume
            nfs:
              server: {{ .Values.nfs.server }}
              path: {{ .Values.nfs.path }}
