apiVersion: batch/v1
kind: CronJob
metadata:
  name: youtube-dl-{{ .Values.streamer.name }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: youtube-dl-{{ .Values.streamer.name }}
        spec:
          serviceAccountName: youtube-dl-{{ .Values.streamer.name }}
          containers:
          - name: youtube-dl-{{ .Values.streamer.name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            envFrom:
            - configMapRef:
                name: youtube-dl-config-{{ .Values.streamer.name }}
            volumeMounts:
            - name: twitch-volume
              mountPath: /download
        {{- if .Values.cleanup.enabled }}
          - name: youtube-dl-{{ .Values.streamer.name }}-cleanup
            image: busybox
            command: ["/bin/sh", "-c"]
            args:
              - |
                # List files older than a specified time to check what would be deleted
                echo "Listing files older than {{ .Values.cleanup.daysOld }} days:"
                find /download/{{ .Values.streamer.twitchName }} -type f -mtime +{{ .Values.cleanup.daysOld }} -name '*.mp4'
                # Uncomment the next line to enable deletion
                find /download/{{ .Values.streamer.twitchName }} -type f -mtime +{{ .Values.cleanup.daysOld }} -name '*.mp4' -exec rm {} +
                echo "Cleanup completed."
            volumeMounts:
              - name: twitch-volume
                mountPath: /download
        {{- end }}
          restartPolicy: OnFailure
          volumes:
          - name: twitch-volume
            nfs:
              server: {{ .Values.nfs.server }}
              path: {{ .Values.nfs.path }}
