name: Build docker images with reusable actions.

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  # Job to run the reusable workflow for release and image push
  deploy:
    uses: liofal/actions/.github/workflows/build_and_deploy.yml@main
    permissions:
      contents: write # Needed by reusable workflow for semantic-release
      packages: write # Needed by reusable workflow for GHCR push
    secrets: inherit
