name: Update Manifests on Release Tag

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on semantic version tags (e.g., v1.0.0, v2.3.4)

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Need permission to write back to the repository
    steps:
      - name: Checkout code
        # Checkout the main branch to commit changes there, not the tag ref
        uses: actions/checkout@v4
        with:
          ref: main # Checkout main branch
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        # Extract the tag name (e.g., v1.2.3) and remove the leading 'v'
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Log extracted version
        run: echo "Updating manifests to version ${{ env.VERSION }}"

      - name: Update Chart.yaml
        run: |
          # Use the version extracted from the tag
          sed -i "s#^version:.*#version: ${{ env.VERSION }}#g" kube/charts/Chart.yaml
          sed -i "s#^appVersion:.*#appVersion: \"${{ env.VERSION }}\"#g" kube/charts/Chart.yaml

      - name: Update values.yaml
        run: |
          sed -i "s#tag:.*#tag: ${{ env.VERSION }}#g" kube/charts/values.yaml

      - name: Update docker-compose.yml
        run: |
          sed -i "s#image: ghcr.io/liofal/youtube-dl:.*#image: ghcr.io/liofal/youtube-dl:${{ env.VERSION }}#g" docker-compose.yml

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add kube/charts/Chart.yaml kube/charts/values.yaml docker-compose.yml
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            # Commit to the main branch
            git commit -m "chore: update manifests to version ${{ env.VERSION }} [skip ci]"
          fi

      - name: Push changes
        # Push the commit to the main branch
        run: git push origin main
